# Author Haris Khan
# Email: haris.khan@zifornd.com



configfile: "config/config.yaml"

report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/fastq.smk"
include: "rules/trim.smk"
include: "rules/fastqc.smk"
include: "rules/genomepy.smk"
include: "rules/bowtie.smk"
include: "rules/macs2.smk"
include: "rules/toBigWig.smk"


# Target rule
rule all:
    input:
        get_final_output()
