$schema: "http://json-schema.org/draft-06/schema#"


type: object

properties:

  samples:
    type: string

  organism:
    type: string

  annotation:
    type: string

required:
  - samples
  - organism
  - annotation
