$schema: "http://json-schema.org/draft-06/schema#"


type: object

properties:

  sample:
    type: string

  unit:
    type: string

  organism:
    type: string

  annotation:
    type: string

required:
  - sample
