# Author Haris Khan
# Email: haris.khan@zifornd.com
name: environment
channels:
  - bioconda
  - conda-forge
dependencies:
  - bowtie2 = 2.4.4
  - samtools = 1.3.1
  - fastqc = 0.11.5
  - homer = 4.9
  - multiqc = 1.10.1
  - deeptools = 3.5.1
